name: set-tag-and-switch-traffic
on:
  workflow_call:
    inputs:
      service_name: 
        type: string
        required: true
      app_version: 
        type: string
        required: true
      region: 
        type: string
        required: true
      environment: 
        type: string
        required: true
      project_id: 
        type: string
        required: true
      project_name: 
        type: string
        required: true
      revision_base: 
        type: string
        required: true
      slack_channel: 
        type: string
        required: true

env:
  SERVICE_ACCOUNT: 'cloud-run-test'
  IDENTITY_POOL_NAME: 'cloud-run-test'
  IDENTITY_PROVIDER_NAME: 'github'

jobs:
  set-tag:
    if: ${{ ! contains(github.event.head_commit.message, '[no switch]') }}
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.set_tag.outputs.tag_name }}
    steps:
      - name: debug
        run: |
          echo 'github.event_name: ' ${{ github.event_name }}
          echo 'github.ref_name: ' ${{ github.ref_name }}
          echo 'github.base_ref: ' ${{ github.base_ref }}
          echo 'inputs.is_switch_traffic: ' ${{ inputs.is_switch_traffic }}
          echo 'inputs.app_version: ' ${{ inputs.app_version }}
          echo 'inputs.region: ' ${{ inputs.region }}
          echo 'inputs.environment: ' ${{ inputs.environment }}
          echo 'inputs.project_id: ' ${{ inputs.project_id }}
          echo 'inputs.project_name: ' ${{ inputs.project_name }}
          echo 'inputs.revision_base: ' ${{ inputs.revision_base }}
          echo 'inputs.slack_channel: ' ${{ inputs.slack_channel }}
          cat $GITHUB_EVENT_PATH

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Tag List
        id: get_tag
        run: |
          latest_tag=$(git tag -l --sort=version:refname "${{ inputs.revision_base }}-${{ inputs.app_version }}*" | tail -n 1)
          release_number=$(echo $latest_tag | sed "s/${{ inputs.revision_base }}-${{ inputs.app_version }}-//" | awk '{print $0+1}')
          # release_number=$(echo $latest_tag | sed "s/${{ inputs.revision_base }}-${{ inputs.app_version }}-//" | awk '{print $0}')
          echo "release_number=${release_number}" >> $GITHUB_ENV
          
      - name: Create and Push New Tag
        id: set_tag
        run: |
          tag_name="${{ inputs.revision_base }}-${{ inputs.app_version }}-${{ env.release_number }}"
          # git tag $tag_name
          # git push origin $tag_name
          echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT
          slack_message="動作確認できたらswitch-trafficしてください"
          if [[ '${{ inputs.is_switch_traffic }}' == 'false' ]] ; then
            slack_message="switch-trafficなし"
          fi
          echo $slack_message

  switch-traffic:
    if: ${{ github.event_name == 'push' || inputs.is_switch_traffic == true }}
    needs:
      - set-tag
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    concurrency:
      group: switch-traffic-${{ inputs.environment }}
      cancel-in-progress: true
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      services: ${{ steps.services_list.outputs.services }}
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ inputs.project_id }}/locations/global/workloadIdentityPools/${{ env.IDENTITY_POOL_NAME }}/providers/${{ env.IDENTITY_PROVIDER_NAME }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}@${{ inputs.project_name }}.iam.gserviceaccount.com"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: List Cloud Run services
        id: services_list
        run: |
          services=$(gcloud run services list --region=${{ inputs.region }} --format="value(name)" --filter="metadata.name:${{ inputs.service_name }}*")
          echo 'services<<EOF' >> $GITHUB_OUTPUT
          echo ${services} >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Switch Traffic
        run: |
          for service in ${{ steps.services_list.outputs.services }}; do
            revision="${service}-${{ needs.set-tag.outputs.tag_name }}"
            gcloud run services update-traffic "$service" --region=${{ inputs.region }} --to-revisions $revision=100
            echo "Updated traffic for service $service to revision $revision"
          done

  cleanup-revision-tags:
    needs:
      - switch-traffic
    environment:
      name: wait-${{ inputs.environment }}
    concurrency:
      group: cleanup-${{ inputs.environment }}
      cancel-in-progress: true
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ inputs.project_id }}/locations/global/workloadIdentityPools/${{ env.IDENTITY_POOL_NAME }}/providers/${{ env.IDENTITY_PROVIDER_NAME }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}@${{ inputs.project_name }}.iam.gserviceaccount.com"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Cleanup revision-tags
        run: |
          protected_revision_tags=($(echo "${{ vars.PROTECTED_REVISION_TAGS }}" | tr ',' ' '))
          for service in ${{ needs.switch-traffic.outputs.services }}; do
            # PROTECTED_REVISION_TAGSの中身があればArtifact Registryイメージに保護用のタグを付与する
            for protected_revision_tag in "${protected_revision_tags[@]}"; do
                # リビジョンの存在確認
                image_url=$(gcloud run revisions describe "${service}-${protected_revision_tag}" --region=${{ env.REGION }} --format="value(image)" 2>/dev/null || echo "")
                if [[ $protected_revision_tag == ${{ inputs.revision_base }}* ]] && [[ -n "$image_url" ]]; then
                  # Artifact Registryイメージ保護
                  image_url=$(echo $image_url | sed 's|gcr.io/${{ inputs.project_name }}|us-docker.pkg.dev/${{ inputs.project_name }}/gcr.io|g')
                  tag_name="protected-vars-${protected_revision_tag}"
                  gcloud artifacts docker tags add "${image_url}" "${image_url%@*}:${tag_name}"
                fi
            done
            # 下記に該当しないリビジョンのタグを抽出する
            # ・トラフィックが割り当てられている
            # ・pullrequestまたはreadyから始まるリビジョンタグが付いている
            # PROTECTED_REVISION_TAGSに含まれるリビジョンである
            traffic=$(gcloud run services describe "$service" --region=${{ inputs.region }} --format="json(spec.traffic)")
            echo $traffic
            delete_tags=$(echo "$traffic" | jq -r --argjson values "$(jq -n --argjson arr '["${protected_revision_tags[@]}"]' '$arr')" '
              .spec.traffic
              | group_by(.revisionName)
              | map(select(
                  all(.percent == null) and all((.tag | startswith("pullrequest") | not) and (.tag | startswith("protected") | not) and (.tag | startswith("ready") | not)) and (.revisionName as $rev | $values | index($rev) | not)
                ))
              | map(.[0].tag)
              | join(",")
            ')
            echo "$delete_tags"
            # いらないリビジョンタグを消す
            gcloud run services update-traffic "$service" --region=${{ inputs.region }} --remove-tags="$delete_tags"
          done
