name: Deployment

on:
  push:
    branches:
      - master
      - staging
      
jobs:
  set-tag:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'build...'
  switch-traffic-prod:
    needs: set-tag
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo 'deploy...'
  switch-traffic-stg:
    needs: set-tag
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: deploy
        run: echo 'deploy...'
  cleanup-revision-tags:
    needs: 
      - switch-traffic-prod
      - switch-traffic-stg
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: echo 'check...'
